# labs_price_list.py
# ============================================================
#  قائمة الأسعار القابلة للتعديل
#  يمكن استبدال هذا الملف عند مشاركة البرنامج مع زملاء آخرين
#  تم التحديث من price_list.txt بتاريخ 22-Jun-2026
# ============================================================

LABS_DB = {
    "Allergy Screen": [
        {"name": "IgE Food allergy test panel", "price": 2500, "result_days": 5, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "IgE for milk allergy Rast", "price": 1300, "result_days": 5, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "IgE Inhalant allergy panel", "price": 2000, "result_days": 5, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "IgE Specific Rast Gluten", "price": 1000, "result_days": 7, "collection_notes": "2 ml serum, frozen"},
        {"name": "Mixed Allergy Panel (Food &", "price": 4000, "result_days": 5, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Pediatric Panel (Food &", "price": 2500, "result_days": 5, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Rast for drugs", "price": 2500, "result_days": 3, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Tuberculin Skin Test", "price": 250, "result_days": 1, "collection_notes": "Skin test"},
    ],
    "Antiphospholipid antibody syndrome": [
        {"name": "Anti Cardiolipin  IgG (ACL IgG)", "price": 700, "result_days": 6, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Anti Cardiolipin  IgM (ACL IgM)", "price": 700, "result_days": 6, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Anti-Phospholipid IgG (APL IgG)", "price": 650, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Anti-Phospholipid IgM (APL IgM)", "price": 650, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Lupus Anticoagulant", "price": 600, "result_days": 1, "collection_notes": "2.0 ml. frozen citrated plasma"},
    ],
    "Ascitic Fluid Chemistry Profile": [
        {"name": "Albumin (Ascitic Fluid)", "price": 100, "result_days": 1, "collection_notes": "Fluid, Ascitic Fluid"},
        {"name": "Ascitic Fluid Examination", "price": 550, "result_days": 2, "collection_notes": "Fluid, Ascitic Fluid"},
        {"name": "Glucose (Ascitic Fluid)", "price": 80, "result_days": 1, "collection_notes": "Fluid, Ascitic Fluid"},
        {"name": "LDH (Ascitic Fluid)", "price": 250, "result_days": 1, "collection_notes": "Fluid, Ascitic Fluid"},
        {"name": "Total Protein (Ascitic Fluid)", "price": 120, "result_days": 1, "collection_notes": "Fluid, Ascitic Fluid"},
    ],
    "Autoimmune diseases": [
        {"name": "Acetylcholine receptor Ab", "price": 3000, "result_days": 20, "collection_notes": "2 ml serum/ refrigerated"},
        {"name": "AChE (Acetylcholinesterase)", "price": 1500, "result_days": 15, "collection_notes": "2.0 ml. frozen  plasma/EDTA"},
        {"name": "Actin Antibodies", "price": 1700, "result_days": 15, "collection_notes": "2 ml serum, frozen"},
        {"name": "Activated protein C resistance", "price": 2500, "result_days": 7, "collection_notes": "2.0 ml. frozen citrated plasma 3.8%"},
        {"name": "ANA (Antinuclear Ab)", "price": 500, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "ANA (Antinuclear Ab) titre by IF", "price": 800, "result_days": 3, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "ANA (Immunoblot technique)", "price": 1800, "result_days": 3, "collection_notes": "3 ml serum/ refrigerated"},
        {"name": "ANCA - C", "price": 1000, "result_days": 3, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "ANCA - P", "price": 1000, "result_days": 3, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "ANCA (Anti neutrophil", "price": 1000, "result_days": 3, "collection_notes": "1.0 ml. Serum"},
        {"name": "Anti CCP", "price": 1400, "result_days": 2, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Anti Centromere Ab", "price": 600, "result_days": 7, "collection_notes": "1.0 ml. Serum"},
        {"name": "Anti Endomysial IgA (EMA IgA)", "price": 2500, "result_days": 10, "collection_notes": "2 ml serum, frozen"},
        {"name": "Anti Endomysial IgG (EMA IgG)", "price": 2500, "result_days": 10, "collection_notes": "2 ml serum, frozen"},
        {"name": "Anti Endomysial IgM (EMA IgM)", "price": 2500, "result_days": 10, "collection_notes": "2 ml serum, frozen"},
        {"name": "Anti Gad Abs", "price": 2600, "result_days": 8, "collection_notes": "2 ml serum, frozen"},
        {"name": "Anti Hepatic Soluble Antigens", "price": 3500, "result_days": 10, "collection_notes": "2 ml serum, frozen"},
        {"name": "Anti Hepatic Soluble Antigens", "price": 3500, "result_days": 10, "collection_notes": "2 ml serum, frozen"},
        {"name": "Anti Hepatic Soluble Antigens", "price": 3500, "result_days": 10, "collection_notes": "2 ml serum, frozen"},
        {"name": "Anti Hepatic Soluble Antigens", "price": 3500, "result_days": 10, "collection_notes": "2 ml serum, frozen"},
        {"name": "Anti Hepatic Soluble Antigens", "price": 3500, "result_days": 10, "collection_notes": "2 ml serum, frozen"},
        {"name": "Anti Hepatic Soluble Antigens", "price": 3500, "result_days": 10, "collection_notes": "2 ml serum, frozen"},
        {"name": "Anti Insulin Abs.", "price": 2500, "result_days": 15, "collection_notes": "2 ml serum, frozen"},
        {"name": "Anti intrinsic factor Abs.", "price": 3000, "result_days": 8, "collection_notes": "2 ml serum, frozen"},
        {"name": "Anti Jo1 Ab", "price": 400, "result_days": 7, "collection_notes": "1.0 ml. Serum"},
        {"name": "Anti Keratin Ab", "price": 1000, "result_days": 7, "collection_notes": "1.0 ml. Serum"},
        {"name": "Anti LKM (Liver Kidney", "price": 600, "result_days": 5, "collection_notes": "1.0 ml. Serum"},
        {"name": "Anti MAG Antibodies IgG", "price": 2000, "result_days": 30, "collection_notes": "2 ml serum, frozen"},
        {"name": "Anti MCV Abs.", "price": 1800, "result_days": 7, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Anti Musk Abs (Muscle Specific", "price": 3600, "result_days": 30, "collection_notes": "1.0 ml. frozen serum"},
        {"name": "Anti Ovarian antibodies IgG", "price": 1900, "result_days": 15, "collection_notes": "2 ml serum, frozen"},
        {"name": "Anti Proteinase-3", "price": 550, "result_days": 3, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Anti striated muscle Abs", "price": 1000, "result_days": 7, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Anti-Deamidated gliadin peptide", "price": 600, "result_days": 7, "collection_notes": "2 ml serum/refrigerated"},
        {"name": "Anti-Gliadin IgA", "price": 1200, "result_days": 3, "collection_notes": "2 ml serum/refrigerated"},
        {"name": "Anti-Gliadin IgG", "price": 1200, "result_days": 3, "collection_notes": "2 ml serum/refrigerated"},
        {"name": "Anti-Gliadin IgM", "price": 1200, "result_days": 3, "collection_notes": "2 ml serum/refrigerated"},
        {"name": "Anti-Histone Ab", "price": 550, "result_days": 7, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Anti-Mitochondrial Abs (AMA)", "price": 700, "result_days": 3, "collection_notes": "1.0 ml. Serum"},
        {"name": "Anti-Parietal Cell Abs  (APCA)", "price": 1000, "result_days": 15, "collection_notes": "1.0 ml. Serum"},
        {"name": "Anti-phospholipase A2 Abs", "price": 7000, "result_days": 23, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Anti-PLA2R (Anti phospholipase", "price": 3900, "result_days": 30, "collection_notes": "2 ml serum, frozen"},
        {"name": "Anti-Reticulin Abs", "price": 350, "result_days": 7, "collection_notes": "1.0 ml. Serum"},
        {"name": "Anti-Ribosomal RNA", "price": 1200, "result_days": 10, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Anti-RNP Abs", "price": 850, "result_days": 3, "collection_notes": "1.0 ml. Serum"},
        {"name": "Anti-Scl 70 Abs", "price": 1000, "result_days": 3, "collection_notes": "1.0 ml. Serum"},
        {"name": "Anti-Smith Abs", "price": 1000, "result_days": 4, "collection_notes": "1.0 ml. Serum"},
        {"name": "Anti-Smooth muscle Abs (ASMA)", "price": 800, "result_days": 3, "collection_notes": "1.0 ml. Serum"},
        {"name": "Anti-Sperm Abs (IgG)", "price": 800, "result_days": 3, "collection_notes": "1.0 ml semen or cervical mucus or serum"},
        {"name": "Anti-SSA (Ro) Abs", "price": 1000, "result_days": 3, "collection_notes": "1.0 ml. Serum"},
        {"name": "Anti-SSB (La) Abs", "price": 1000, "result_days": 3, "collection_notes": "1.0 ml. Serum"},
        {"name": "Aquoporin 4 (neuromyelitis optic", "price": 3960, "result_days": 11, "collection_notes": "Frozen CSF"},
        {"name": "Aquoporin 4 (neuromyelitis optic", "price": 5940, "result_days": 7, "collection_notes": "2 ml serum, frozen"},
        {"name": "ASCA (IgA)", "price": 1000, "result_days": 8, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "ASCA (IgG)", "price": 1000, "result_days": 7, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "ASOT(Anti-Streptolysin-O)(Quanti", "price": 350, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "B2-Glycoprotein Abs(IgG)", "price": 1000, "result_days": 3, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "B2-Glycoprotein Abs(IgM)", "price": 1000, "result_days": 3, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Cow Milk (class)", "price": 1300, "result_days": 5, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "ds-DNA (Anti ds-DNA Abs)", "price": 300, "result_days": 3, "collection_notes": "1.0 ml. Serum"},
        {"name": "Islet cell Ab", "price": 1800, "result_days": 7, "collection_notes": "1.0 ml. Serum"},
        {"name": "NK Cells (natural Killer cells", "price": 1700},
        {"name": "Platelet Antibodies (Direct)", "price": 1200, "result_days": 7, "collection_notes": "2 tubes Heparinized Blood + 2 tubes EDTA Blood"},
        {"name": "Platelet Antibodies (Indirect)", "price": 1200, "result_days": 3, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Soluble Liver Antigen (SLA-Ab)", "price": 2500, "result_days": 10, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Tissue transglutaminase Ab (IgA)", "price": 1000, "result_days": 3, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Tissue transglutaminase Ab (IgG)", "price": 1000, "result_days": 3, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Von Willebrand Factor (VWF)", "price": 2500, "result_days": 8, "collection_notes": "2 ml frozen. citrated plasma"},
    ],
    "BLOOD GASES": [
        {"name": "Amino Acids in blood", "price": 3300, "result_days": 15, "collection_notes": "2.0 ml. Serum or plasma ( Lithium heparinized or EDTA)"},
        {"name": "Blood Gases", "price": 1000, "result_days": 1, "collection_notes": "2 ml anaerobic heparinized blood send immed."},
        {"name": "Blood Gases  Base Excess", "price": 0, "result_days": 1, "collection_notes": "Heparinized Blood"},
        {"name": "Blood Gases  HCO3", "price": 0, "result_days": 1, "collection_notes": "Heparinized Blood"},
        {"name": "Blood Gases  pCO2", "price": 0, "result_days": 1, "collection_notes": "Heparinized Blood"},
        {"name": "Blood Gases  pH", "price": 0, "result_days": 1, "collection_notes": "Heparinized Blood"},
        {"name": "Blood Gases  pO2", "price": 0, "result_days": 1, "collection_notes": "Heparinized Blood"},
        {"name": "Blood Gases TCO2", "price": 0},
        {"name": "Blood pH", "price": 150, "result_days": 1, "collection_notes": "2 ml anaerobic heparinized blood"},
        {"name": "Osmotic fragility test", "price": 250, "result_days": 1, "collection_notes": "10 ml Heparin Blood"},
    ],
    "Blood Glucose": [
        {"name": "FBG", "price": 120, "result_days": 1, "collection_notes": "Plasma/floride"},
        {"name": "GLP-1 (Glucagon like peptide)", "price": 3000, "result_days": 60, "collection_notes": "2.0 ml. frozen EDTA plasma"},
        {"name": "Glucose 1 hr (100 gm Glucose)", "price": 100, "result_days": 1, "collection_notes": "2ml  plasma/Fluride"},
        {"name": "Glucose 1 hr (50 gm Glucose)", "price": 100, "result_days": 1, "collection_notes": "Plasma/floride"},
        {"name": "Glucose 1 hr (75 gm Glucose)", "price": 100},
        {"name": "Glucose 2 hr (100 gm Glucose)", "price": 100, "result_days": 1, "collection_notes": "Plasma/fluride"},
        {"name": "Glucose 2 hr (50 gm Glucose)", "price": 100, "result_days": 1, "collection_notes": "Plasma/Floride"},
        {"name": "Glucose 2 hr (75 gm Glucose)", "price": 100},
        {"name": "Glucose Tolerance  1 hr", "price": 100, "result_days": 1, "collection_notes": "plasma/floride"},
        {"name": "Glucose Tolerance  2 hrs", "price": 100, "result_days": 1, "collection_notes": "plasma/floride"},
        {"name": "Glucose Tolerance 1.5 hr", "price": 100, "result_days": 1, "collection_notes": "Plasma/Floride"},
        {"name": "Glucose Tolerance Curve", "price": 420, "result_days": 1, "collection_notes": "2ml  plasma/Fluride"},
        {"name": "HbA1C", "price": 400, "result_days": 1, "collection_notes": "Whole blood/EDTA"},
        {"name": "HOMA1-IR", "price": 550, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "PPBG", "price": 100, "result_days": 1, "collection_notes": "2.0 ml serum or plasma floride"},
        {"name": "RBG", "price": 120, "result_days": 1, "collection_notes": "Plasma/Floride"},
    ],
    "Blood Group": [
        {"name": "ABO", "price": 85, "result_days": 1, "collection_notes": "Whole blood/EDTA"},
        {"name": "Blood Rh", "price": 90, "result_days": 1, "collection_notes": "EDTA Plasma"},
        {"name": "Direct Coombs", "price": 280, "result_days": 1, "collection_notes": "1.0 ml EDTA blood"},
        {"name": "Indirect Coombs", "price": 250, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Rh Antibody Titre (In direct", "price": 350, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
    ],
    "Blood Picture": [
        {"name": "Hb (hemoglobin)", "price": 130, "result_days": 1, "collection_notes": "1.0 ml EDTA blood"},
        {"name": "Hct", "price": 130, "result_days": 1, "collection_notes": "1.0 ml EDTA blood"},
        {"name": "Hgb And Indices", "price": 70, "result_days": 1, "collection_notes": "1.0 ml EDTA blood"},
        {"name": "Platelets", "price": 200, "result_days": 1, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "RBCs", "price": 150, "result_days": 1},
        {"name": "WBCs", "price": 100, "result_days": 1},
        {"name": "WBCs (Diff.)", "price": 150, "result_days": 1},
    ],
    "Body Fluid": [
        {"name": "Albumin (Body Fluid)", "price": 120, "result_days": 1, "collection_notes": "Fluid"},
        {"name": "Beta Trace Protein", "price": 3000, "result_days": 15, "collection_notes": "2 ml csf fluid"},
        {"name": "Chloride (Body Fluid)", "price": 300, "result_days": 1, "collection_notes": "Fluid"},
        {"name": "Creatinine (Body Fluid)", "price": 100, "result_days": 1, "collection_notes": "Fluid"},
        {"name": "Gene Xpert - MTB/RIF", "price": 3000, "result_days": 5, "collection_notes": "Any biological fluid at least 2 ml"},
        {"name": "Glucose (Body Fluid)", "price": 100, "result_days": 1, "collection_notes": "Fluid"},
        {"name": "LDH (Body Fluid)", "price": 250, "result_days": 1, "collection_notes": "Fluid"},
        {"name": "Total Protein (Body Fluid)", "price": 120, "result_days": 1, "collection_notes": "Fluid"},
    ],
    "Cardiac Profile": [
        {"name": "Brain Natriuretic Peptide (BNP)", "price": 1200, "result_days": 8, "collection_notes": "2.0 ml. EDTA plasma - refrigerated"},
        {"name": "CK (MB)", "price": 350, "result_days": 1, "collection_notes": "Serum"},
        {"name": "CK(MM)", "price": 800, "result_days": 3, "collection_notes": "Serum 1.0 ml. Refrigerated"},
        {"name": "CPK (Total)", "price": 350, "result_days": 1, "collection_notes": "Serum"},
        {"name": "CPK Isoenzymes", "price": 2500, "result_days": 15, "collection_notes": "1.0 ml. frozen serum"},
        {"name": "Homocysteine", "price": 1200, "result_days": 2, "collection_notes": "Serum Or  Plasma /Heparine"},
        {"name": "LDH", "price": 250, "result_days": 1, "collection_notes": "1.0 ml serum"},
        {"name": "Myoglobin in serum", "price": 350, "result_days": 6, "collection_notes": "1.0 ml. Serum"},
        {"name": "Pro-Brain Natriuretic Peptide", "price": 1500, "result_days": 2, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Troponin (I)", "price": 450, "result_days": 1, "collection_notes": "Serum  Or  Heparinized Plasma"},
        {"name": "Troponin (T) high sensitive", "price": 600, "result_days": 5, "collection_notes": "Serum  Or  Plasma"},
    ],
    "Coagulation Profile": [
        {"name": "Anti-thrombin III Abs", "price": 800, "result_days": 7, "collection_notes": "2.0 ml. frozen citrated plasma"},
        {"name": "Bleeding Time", "price": 70, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "C5 (Complement. C5)", "price": 1600, "result_days": 15, "collection_notes": "2 ml serum, frozen"},
        {"name": "Clotting Time", "price": 70, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Complement. (50%) CH50", "price": 1100, "result_days": 15, "collection_notes": "2 ml serum, frozen"},
        {"name": "D-dimer", "price": 750, "result_days": 1, "collection_notes": "2.0 ml. frozen citrated plasma"},
        {"name": "Factor II (F, 2)", "price": 1200, "result_days": 15, "collection_notes": "2ml frozen citrated plasma platelet poor"},
        {"name": "Factor IX  (F. 9)", "price": 1300, "result_days": 10, "collection_notes": "2ml citrated plasma platelet poor"},
        {"name": "Factor V  (F. 5)", "price": 1300, "result_days": 10, "collection_notes": "2ml frozen citrated plasma platelet poor"},
        {"name": "Factor VII  (F. 7)", "price": 1350, "result_days": 10, "collection_notes": "2ml frozen citrated plasma platelet poor"},
        {"name": "Factor VIII  (F. 8)", "price": 1750, "result_days": 10, "collection_notes": "2ml frozen citrated plasma platelet poor"},
        {"name": "Factor VIII Inhibitor", "price": 1750, "result_days": 3, "collection_notes": "2 ml citrated plasma platelet poor in plastic tube"},
        {"name": "Factor X  (F. 10)", "price": 1450, "result_days": 10, "collection_notes": "2ml frozen citrated plasma platelet poor"},
        {"name": "Factor XI  (F. 11)", "price": 1300, "result_days": 10, "collection_notes": "2ml frozen citrated plasma platelet poor"},
        {"name": "Factor XII  (F. 12)", "price": 700, "result_days": 10, "collection_notes": "2ml frozen citrated plasma platelet poor"},
        {"name": "Factor XIII (F,13)", "price": 1450, "result_days": 10, "collection_notes": "2.0 ml. frozen citrated plasma"},
        {"name": "Fibrinogen Level", "price": 300, "result_days": 2, "collection_notes": "2.0 ml. frozen citrated plasma"},
        {"name": "Platelet aggregation to ADP", "price": 1600, "result_days": 1, "collection_notes": "2 Tube Whole blood/EDTA and 6 Tube Whole blood/citrate"},
        {"name": "Platelet aggregation to", "price": 1600, "result_days": 3, "collection_notes": "2 Tube Whole blood/EDTA and 6 Tube Whole blood/citrate"},
        {"name": "PT", "price": 180, "result_days": 1, "collection_notes": "Citrated Plasma"},
        {"name": "PTT", "price": 200, "result_days": 1, "collection_notes": "Citrated Plasma"},
        {"name": "PTT after mixing studies", "price": 200},
        {"name": "Thrombin Time (TT)", "price": 300, "result_days": 1, "collection_notes": "1.8 ml. blood on 0.2 ml Citrate and sent immediately frozen"},
        {"name": "Von Willebrand Factor (VWF) Conc", "price": 2500, "result_days": 8, "collection_notes": "2 ml frozen. citrated plasma"},
    ],
    "CSF Chemistry Profile": [
        {"name": "AFP (CSF)", "price": 600, "result_days": 1, "collection_notes": "2 ml csf fluid"},
        {"name": "Albumin (CSF)", "price": 120, "result_days": 1, "collection_notes": "CSF"},
        {"name": "Chloride (CL) in CSF", "price": 300, "result_days": 1, "collection_notes": "2 ml csf fluid"},
        {"name": "CSF examination (Pleural,", "price": 850, "result_days": 1, "collection_notes": "2 ml csf fluid"},
        {"name": "CSF Oligoclonal band", "price": 2500, "result_days": 10, "collection_notes": "2 ml csf fluid"},
        {"name": "Glucose (CSF)", "price": 120, "result_days": 1, "collection_notes": "2 ml csf fluid"},
        {"name": "LDH (CSF)", "price": 250, "result_days": 1, "collection_notes": "CSF"},
        {"name": "Magnesium (Mg) CSF", "price": 260, "result_days": 1, "collection_notes": "2 ml csf fluid"},
        {"name": "Total Protein (CSF)", "price": 120, "result_days": 1, "collection_notes": "2 ml csf fluid"},
    ],
    "Culture and Sensitivity": [
        {"name": "Anal Swab Examination", "price": 100, "result_days": 1, "collection_notes": "swab"},
        {"name": "Ascitic Fluid Culture", "price": 900, "result_days": 4, "collection_notes": "Fluid, Ascitic Fluid"},
        {"name": "Ascitic Fluid Culture for Fungi", "price": 450, "result_days": 5, "collection_notes": "Fluid"},
        {"name": "Blood Culture", "price": 600, "result_days": 13, "collection_notes": "Special sterile bottles"},
        {"name": "Body Fluid Culture", "price": 700, "result_days": 1, "collection_notes": "FLUID OR FILM"},
        {"name": "Bone marrow examination", "price": 1000, "result_days": 5, "collection_notes": "Bone Marrow"},
        {"name": "Breast Discharge Culture", "price": 450, "result_days": 5, "collection_notes": "swap of discharge"},
        {"name": "Conjuntival Swab Culture", "price": 450, "result_days": 5, "collection_notes": "swab"},
        {"name": "CSF Culture and Sensitivity", "price": 450, "result_days": 5, "collection_notes": "2 ml csf fluid"},
        {"name": "Fungus C/S", "price": 450, "result_days": 22, "collection_notes": "skin, nail , hair"},
        {"name": "Gum Discharge Culture", "price": 450, "result_days": 5, "collection_notes": "swab"},
        {"name": "Left Ear Discharge Culture", "price": 350, "result_days": 5, "collection_notes": "swab"},
        {"name": "Left Eye discharge Culture", "price": 350, "result_days": 5, "collection_notes": "swab"},
        {"name": "Nail Culture", "price": 450, "result_days": 4, "collection_notes": "skin, nail scrap"},
        {"name": "Nasal Swab Culture", "price": 450, "result_days": 4, "collection_notes": "swab"},
        {"name": "Nasal Swab for MRSA", "price": 450, "result_days": 4, "collection_notes": "Nasal swab"},
        {"name": "POST-COITAL", "price": 500, "result_days": 1, "collection_notes": "swab"},
        {"name": "Prostatic Discharge Examination", "price": 350, "result_days": 1, "collection_notes": "prostatic secration"},
        {"name": "Prostatic Secreation Culture", "price": 450, "result_days": 5, "collection_notes": "Fluid"},
        {"name": "Pus Culture and Sensitivity", "price": 450, "result_days": 5, "collection_notes": "swab / wound"},
        {"name": "Pus From Wound Culture", "price": 450, "result_days": 5, "collection_notes": "swab from inside wound"},
        {"name": "Right Ear Discharge Culture", "price": 450, "result_days": 5, "collection_notes": "swab"},
        {"name": "Right Eye discharge Culture", "price": 450, "result_days": 5, "collection_notes": "swab"},
        {"name": "Semen Culture", "price": 450, "result_days": 4, "collection_notes": "Semen"},
        {"name": "Sputum Culture", "price": 450, "result_days": 4, "collection_notes": "Sputum"},
        {"name": "Sputum Culture for AFB", "price": 1200, "result_days": 7, "collection_notes": "Sputum"},
        {"name": "Stool Culture", "price": 500, "result_days": 5, "collection_notes": "Stool"},
        {"name": "Swab C&S", "price": 500, "result_days": 4, "collection_notes": "swab"},
        {"name": "Synovial Fluid Culture", "price": 500, "result_days": 5, "collection_notes": "Fluid, Synovial"},
        {"name": "Synovial Fluid Examination", "price": 900, "result_days": 1, "collection_notes": "Fluid, Synovial"},
        {"name": "TB Culture and Sensitivity", "price": 1600, "result_days": 60, "collection_notes": "Fluid"},
        {"name": "Throat Swab Culture", "price": 450, "result_days": 5, "collection_notes": "swab"},
        {"name": "Ulcer Swab C&S", "price": 450, "result_days": 4, "collection_notes": "swab"},
        {"name": "Urethral Discharge Culture", "price": 450, "result_days": 1, "collection_notes": "swap of discharge"},
        {"name": "Urine Culture", "price": 450, "result_days": 4, "collection_notes": "urine"},
        {"name": "Vaginal Swab Culture", "price": 450, "result_days": 4, "collection_notes": "swab"},
        {"name": "Vulval Swab Exam. C&S", "price": 450, "result_days": 5, "collection_notes": "swab"},
        {"name": "Ziehl Nielsen Stain (one slide)", "price": 150, "result_days": 2, "collection_notes": "FLUID OR FILM"},
    ],
    "Drugs monitoring": [
        {"name": "Cyclosporine (Peak)", "price": 900, "result_days": 5, "collection_notes": "2 ml EDTA blood"},
        {"name": "Cyclosporine (Random)", "price": 900, "result_days": 5, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "Cyclosporine (Trough)", "price": 900, "result_days": 5, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "Depakine (Valporic) Random", "price": 450, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Depakine (Valporic) Trough", "price": 450, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Depakine (Valproic) peak", "price": 450, "result_days": 1, "collection_notes": "1.0 ml serum or plasma"},
        {"name": "Digoxin (Lanoxin)", "price": 400, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Everolimus(Certican)", "price": 2200, "result_days": 10, "collection_notes": "2 ml EDTA blood"},
        {"name": "Lithium", "price": 400, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Methotrexate", "price": 550, "result_days": 2, "collection_notes": "1.0 ml. Serum"},
        {"name": "Phenobarbitone", "price": 250, "result_days": 4, "collection_notes": "1.0 ml. Serum"},
        {"name": "Phenytoin (Epanutin, Dilantin)", "price": 500, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Tacrolimus (FK506), Peak", "price": 1600, "result_days": 4, "collection_notes": "2.0 ml. EDTA blood refrigerated"},
        {"name": "Tacrolimus (FK506), Random", "price": 1600, "result_days": 4, "collection_notes": "1.0 ml EDTA blood"},
        {"name": "Tacrolimus (FK506), Trough", "price": 1600, "result_days": 4, "collection_notes": "2 ml EDTA blood"},
        {"name": "Tegretol (Carbamazepine) Peak", "price": 400, "result_days": 1, "collection_notes": "1.0 ml serum  or  heparinized plasma"},
        {"name": "Tegretol (Carbamazepine) Random", "price": 400, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Tegretol (Carbamazepine) Trough", "price": 400, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Theophylline", "price": 1200, "result_days": 8, "collection_notes": "1.0 ml. Serum"},
        {"name": "Vancomycin", "price": 500, "result_days": 7, "collection_notes": "1.0 ml. frozen serum"},
    ],
    "Drugs Of Abuse": [
        {"name": "Alcohol (In blood)", "price": 1200, "result_days": 4, "collection_notes": "2 ml serum, refrigerated or 1 ml urine"},
        {"name": "Alcohol (In Urine)", "price": 1200, "result_days": 1, "collection_notes": "urine"},
        {"name": "Amphetamine", "price": 250, "result_days": 2, "collection_notes": "Fresh urine ,avoid adulteration"},
        {"name": "Bango (Cannabinoids)", "price": 250, "result_days": 1, "collection_notes": "Fresh urine ,avoid adulteration"},
        {"name": "Barbtiurates", "price": 250, "result_days": 1, "collection_notes": "Fresh urine ,avoid adulteration"},
        {"name": "Benzodiazeipines (Valium)", "price": 250, "result_days": 1, "collection_notes": "Fresh urine ,avoid adulteration"},
        {"name": "Cannabinoids (Hashish, Banjo)", "price": 250, "result_days": 1, "collection_notes": "Fresh urine ,avoid adulteration"},
        {"name": "Cocaine", "price": 250, "result_days": 1, "collection_notes": "Fresh urine ,avoid adulteration"},
        {"name": "Codiene (Opiates)", "price": 250, "result_days": 1, "collection_notes": "Fresh urine ,avoid adulteration"},
        {"name": "Cotonine(Nictoine metabolite)", "price": 1450, "result_days": 15, "collection_notes": "2 ml serum, frozen"},
        {"name": "Cotonine(Nictoine metabolite) in", "price": 1450, "result_days": 15, "collection_notes": "10 ml refrigerated morning urine sample , No preservative"},
        {"name": "Ecstasy", "price": 250, "result_days": 1, "collection_notes": "Fresh urine ,avoid adulteration"},
        {"name": "Hashish (Cannabinoids)", "price": 250, "result_days": 1, "collection_notes": "Fresh urine ,avoid adulteration"},
        {"name": "Heroine (Opiates)", "price": 250},
        {"name": "Marijuana (Cannabinoids)", "price": 250, "result_days": 1, "collection_notes": "Fresh urine ,avoid adulteration"},
        {"name": "Methadone", "price": 250, "result_days": 1, "collection_notes": "Fresh urine ,avoid adulteration"},
        {"name": "Morphin (Opiates)", "price": 250, "result_days": 1, "collection_notes": "Fresh urine ,avoid adulteration"},
        {"name": "Nicotine (tobacco - smoking)", "price": 500, "result_days": 4, "collection_notes": "Fresh urine ,avoid adulteration"},
        {"name": "Opiates (Heroine,codiene)", "price": 250, "result_days": 1, "collection_notes": "Fresh urine ,avoid adulteration"},
        {"name": "Phencyclidine(P.C.P)", "price": 300, "result_days": 1, "collection_notes": "Fresh urine ,avoid adulteration"},
        {"name": "Propoxyphene (PPX)", "price": 250},
        {"name": "Toxicology panel", "price": 1500, "result_days": 5, "collection_notes": "urine"},
        {"name": "Tramadol In urine", "price": 300, "result_days": 1, "collection_notes": "urine"},
        {"name": "Tramadol in urine (Quantit)", "price": 650, "result_days": 1, "collection_notes": "5ml. fresh urine"},
    ],
    "Erythrocyte Sedimentation Rate": [
        {"name": "ESR", "price": 120, "result_days": 1, "collection_notes": "1.0 ml EDTA blood"},
    ],
    "Fertility Hormones": [
        {"name": "17-Keto steroids", "price": 1500, "result_days": 7, "collection_notes": "24 hrs. urine 10 ml 6 N. HCL"},
        {"name": "AMH (Anti Mullerian Hormone)", "price": 1300, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Androstenedione", "price": 1500, "result_days": 4, "collection_notes": "1.0 ml. Serum"},
        {"name": "Basal FSH (LH-RH Stimulation)", "price": 250, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Basal LH (LH-RH Stimulation)", "price": 250, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Chromosome  Y microdeletions", "price": 8000, "result_days": 30, "collection_notes": "2.0 ml. EDTA blood refrigerated"},
        {"name": "DHEA", "price": 450, "result_days": 3, "collection_notes": "1.0 ml. Serum"},
        {"name": "DHEA-S", "price": 450, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "DHT (Dihydrotestosterone)", "price": 2500, "result_days": 9, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "E1 (Estrone)", "price": 1700, "result_days": 15, "collection_notes": "1.0 ml. frozen serum"},
        {"name": "E2 (Estradiol)", "price": 300, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "E3 (Estriol)", "price": 650, "result_days": 7, "collection_notes": "1.0 ml. Serum"},
        {"name": "Erythropoitin (EPO) Ab", "price": 1500, "result_days": 3, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Free testosterone index", "price": 450, "result_days": 10, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "FSH", "price": 350, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Inhibin A", "price": 2500, "result_days": 15, "collection_notes": "1.0 ml. Serum"},
        {"name": "Inhibin B", "price": 2500, "result_days": 15, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "LH", "price": 330, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Peak E2 (LH-RH Stimulation)", "price": 300, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Peak FSH (LH-RH Stimulation)", "price": 300, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Peak LH (LH-RH Stimulation)", "price": 300, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Progesterone", "price": 330, "result_days": 1, "collection_notes": "1.0 ml. Serum day 21 peroid"},
        {"name": "Prolactin (PRL)", "price": 330, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "SHBG", "price": 1400, "result_days": 7, "collection_notes": "1.0 ml. Serum"},
        {"name": "Testosterone Free", "price": 500, "result_days": 2, "collection_notes": "1.0 ml. Serum"},
        {"name": "Testosterone Total", "price": 400, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
    ],
    "GENETICS UNIT": [
        {"name": "(MTHFR) gene mutation", "price": 4500, "result_days": 10, "collection_notes": "5.0 ml. EDTA blood refrigerated"},
        {"name": "Babymap (Newborn Screening)", "price": 30000, "result_days": 30, "collection_notes": "2 ml Whole blood /EDTA"},
        {"name": "Calreticulin Mutation CALR", "price": 5100, "result_days": 12, "collection_notes": "3 ml Whole blood /EDTA"},
        {"name": "Chromosomal Micrarray Analysis", "price": 30000, "result_days": 30, "collection_notes": "2 ml Whole blood /EDTA"},
        {"name": "Cystic fibrosis (CFTR gene", "price": 12000, "result_days": 12, "collection_notes": "2 ml EDTA blood"},
        {"name": "Double markers", "price": 2300, "result_days": 12, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Extended metabolic screening", "price": 3000, "result_days": 21, "collection_notes": "3.0 ml. EDTA blood refrigerated"},
        {"name": "Factor V  (Leiden gene study)", "price": 1850, "result_days": 10, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "FISH Choromosome", "price": 2600},
        {"name": "FISH del 11 q", "price": 4000, "result_days": 30, "collection_notes": "2 tubes Heparinized Blood + 2 tubes EDTA Blood"},
        {"name": "FISH del 13 q", "price": 4000, "result_days": 30, "collection_notes": "2 tubes Heparinized Blood + 2 tubes EDTA Blood"},
        {"name": "FISH del 17 p", "price": 5000, "result_days": 30, "collection_notes": "2 tubes Heparinized Blood + 2 tubes EDTA Blood"},
        {"name": "FISH for (11,14) q", "price": 4500},
        {"name": "FISH for 5 q", "price": 4500},
        {"name": "FISH for 7 q", "price": 4500},
        {"name": "Flu Respiratory Panel", "price": 2500, "result_days": 3, "collection_notes": "Nasal Swab or Nasopharyngeal Swab"},
        {"name": "Huntington chorea PCR", "price": 35000, "result_days": 20, "collection_notes": "3 ml Whole blood /EDTA"},
        {"name": "Islet Antigen 2 Ab (IA2)", "price": 2800, "result_days": 10, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Match my genome", "price": 60000, "result_days": 60, "collection_notes": "2 ml Whole blood /EDTA"},
        {"name": "MYELOPROLIFERATIVE MPL", "price": 5500, "result_days": 12, "collection_notes": "3.0 ml EDTA blood"},
        {"name": "Non Invasive prenatal screening", "price": 23000, "result_days": 30, "collection_notes": "Maternal Blood (Streck tube)"},
        {"name": "Philadelphia Chromosome PCR", "price": 4000, "result_days": 10, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "Prothrombin Mutation (factor II", "price": 1800, "result_days": 10, "collection_notes": "2 ml . blood / Edta . refrigerated"},
        {"name": "Quadruple markers", "price": 7000, "result_days": 7, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Respiratory Panel (bacterial", "price": 3000, "result_days": 3, "collection_notes": "Nasal Swab or Nasopharyngeal Swab"},
        {"name": "Respiratory Panel (Viral only)", "price": 5000, "result_days": 3, "collection_notes": "Nasal Swab or Nasopharyngeal Swab"},
        {"name": "Respiratory Panel by PCR", "price": 6500, "result_days": 3, "collection_notes": "Nasal Swab or Nasopharyngeal Swab"},
        {"name": "Thrombophilia gene Profile", "price": 6500, "result_days": 10, "collection_notes": "1.0 ml serum or plasma"},
        {"name": "Triple markers", "price": 1700, "result_days": 7, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Whole exome sequencing (WES)", "price": 30000, "result_days": 30, "collection_notes": "2 ml Whole blood /EDTA"},
    ],
    "GH stimulation test": [
        {"name": "Growth hormone after 0.5 hr", "price": 450, "result_days": 2, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Growth hormone after 1 hr", "price": 450, "result_days": 2, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Growth hormone after 1.5 hrs", "price": 450, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Growth hormone after 2 hrs", "price": 450, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
    ],
    "Heavy Metals": [
        {"name": "Iodines in serum", "price": 400, "result_days": 20, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Manganese", "price": 3500, "result_days": 10, "collection_notes": "2 ml Whole blood /EDTA"},
        {"name": "Mercury (blood)", "price": 1500, "result_days": 12, "collection_notes": "Heparinized Blood"},
    ],
    "HEMATOLOGY": [
        {"name": "Acidified glycerol lysis test", "price": 300, "result_days": 3, "collection_notes": "1 ml Whole blood/EDTA"},
        {"name": "CBC", "price": 400, "result_days": 1, "collection_notes": "1.0 ml EDTA blood"},
        {"name": "Cross matching", "price": 0, "result_days": 1, "collection_notes": "1.0 ml. Serum or plasma (heparinized or EDTA)"},
        {"name": "Cross matching (including viral", "price": 360, "result_days": 1},
        {"name": "Eosin -5- maleimide binding test", "price": 1700, "result_days": 10, "collection_notes": "3 ml Whole blood/EDTA"},
        {"name": "Fecal Immunochemical Test (FIT)", "price": 1000, "result_days": 7, "collection_notes": "Fresh stool"},
        {"name": "Fibro test/Acti test", "price": 4000, "result_days": 7, "collection_notes": "5 ml fasting serum"},
        {"name": "Folic acid (RBCs)", "price": 1100, "result_days": 7, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "G6PD (Qualitative)", "price": 400, "result_days": 1, "collection_notes": "1.0 ml EDTA blood"},
        {"name": "G6PD (Quantitative)", "price": 400, "result_days": 1, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "LE cell", "price": 400, "result_days": 1},
        {"name": "Natural killer cells Funcation", "price": 1600, "result_days": 5, "collection_notes": "5 ml EDTA blood"},
        {"name": "Occult Blood In Stool (FOB)", "price": 250, "result_days": 1, "collection_notes": "Fresh stool"},
        {"name": "Procalcitonin (PCT)", "price": 2500, "result_days": 3, "collection_notes": "2 ml serum, frozen"},
        {"name": "PRP", "price": 350},
        {"name": "PRP 1", "price": 350},
        {"name": "Retics", "price": 150, "result_days": 1, "collection_notes": "1.0 ml EDTA blood"},
    ],
    "Hemoglobin Electrophoresis": [
        {"name": "HB-A1(Hemoglobin A1", "price": 940, "result_days": 7, "collection_notes": "1.0 ml EDTA blood"},
        {"name": "Hemoglobin electrophoresis by", "price": 600, "result_days": 7, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "Hemoglobin electrophoresis by", "price": 4000, "result_days": 25, "collection_notes": "2.0 ml EDTA blood"},
    ],
    "Hepatitis Markers": [
        {"name": "HAV IgG Ab", "price": 400, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "HAV IgM Ab", "price": 400, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "HBc IgG", "price": 350, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "HBc IgM Ab (Hepatitis B core )", "price": 350, "result_days": 1, "collection_notes": "1.0 ml. Serum or plasma (heparinized ,sod. Citrate,or EDTA)"},
        {"name": "HBe Ab", "price": 300, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "HBe Ag", "price": 300, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "HBs Ab", "price": 300, "result_days": 1, "collection_notes": "1.0 ml. Serum or plasma (heparinized or EDTA)"},
        {"name": "HBs Ab (Quanti)", "price": 300, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "HBs Ag", "price": 300, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "HCV IgG", "price": 300, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "HCV lgM", "price": 750, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "HDV Abs  (total)", "price": 1200, "result_days": 7, "collection_notes": "1.0 ml. Serum"},
        {"name": "HDV IgG", "price": 1200, "result_days": 7, "collection_notes": "1.0 ml. Serum"},
        {"name": "HDV IgM", "price": 1200, "result_days": 7, "collection_notes": "1.0 ml. Serum"},
        {"name": "HEV Ab IgG", "price": 1500, "result_days": 7, "collection_notes": "1.0 ml. Serum"},
        {"name": "HEV Ab IgM", "price": 1500, "result_days": 7, "collection_notes": "1.0 ml. Serum"},
    ],
    "HOMA2": [
        {"name": "HOMA2-%B", "price": 0},
        {"name": "HOMA2-%S", "price": 0},
        {"name": "HOMA2-IR", "price": 0},
        {"name": "QUICKI", "price": 0},
    ],
    "Immunoglobulins": [
        {"name": "Asperagillus fumigatus abs", "price": 2000, "result_days": 10, "collection_notes": "2 ml serum, frozen"},
        {"name": "C2 (Complement 2)", "price": 1700, "result_days": 10, "collection_notes": "1.0 ml. Serum"},
        {"name": "C3 (Complement. C3)", "price": 600, "result_days": 1, "collection_notes": "1.0 ml. frozen serum"},
        {"name": "C4 (Complement. C4)", "price": 600, "result_days": 1, "collection_notes": "1.0 ml. frozen serum"},
        {"name": "Complement Level C1q", "price": 1500, "result_days": 15, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Complement Level CH100", "price": 1100, "result_days": 15, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "ENA Profile", "price": 2000, "result_days": 3, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Food print IgE (20 test)", "price": 3300, "result_days": 3, "collection_notes": "3 ml serum"},
        {"name": "Food print IgE (30 test)", "price": 5500, "result_days": 3, "collection_notes": "3 ml serum/refrigerated"},
        {"name": "Food print IgG (220 test)", "price": 12500, "result_days": 11, "collection_notes": "3 ml serum/ refrigerated"},
        {"name": "Food print IgG (60 test)", "price": 8500, "result_days": 10, "collection_notes": "3 ml serum/ refrigerated"},
        {"name": "Haptoglobin", "price": 500, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "IgA (Immunoglobulin A)", "price": 400, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "IgD (Immunoglobulin D)", "price": 1200, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "IgE (Total)", "price": 400, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "IgG (Immunoglobulin G)", "price": 350, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "IgG Index CSF", "price": 2000},
        {"name": "IgG4", "price": 1500},
        {"name": "IgM (Immunoglobulin M)", "price": 350, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Immunofixation Electrophoresis", "price": 3000, "result_days": 10, "collection_notes": "2 ml serum, refrigerated + 10 ml urine"},
        {"name": "Immunofixation Electrophoresis", "price": 3000, "result_days": 10, "collection_notes": "urine"},
    ],
    "IMMUNOLOGY": [
        {"name": "C1 Esterase inhibitor", "price": 1350, "result_days": 10, "collection_notes": "2.0 ml. EDTA plasma - refrigerated"},
        {"name": "Cholinesterase", "price": 800, "result_days": 3, "collection_notes": "2 ml serum, frozen"},
        {"name": "Filaria Abs", "price": 1200, "result_days": 10, "collection_notes": "2.0 ml serum or plasma"},
        {"name": "Interleukin-6", "price": 2500, "result_days": 7, "collection_notes": "2 ml serum, frozen"},
        {"name": "Liver Cytosol Antigen Abs.", "price": 800, "result_days": 7, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "TB Gold Quantiferon", "price": 3800, "result_days": 12, "collection_notes": "4 Tube of 3 ml Whole blood /Heparin"},
        {"name": "Thiopurine methyl transferase", "price": 5000, "result_days": 21, "collection_notes": "5 ml  W.blood/EDTA"},
        {"name": "Tissue Polypeptide Anigen (TPA)", "price": 1200, "result_days": 15, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Tissue Polypeptide Specific", "price": 1200, "result_days": 15, "collection_notes": "2 ml serum, refrigerated"},
    ],
    "Immunophenotyping": [
        {"name": "Anti Kappa", "price": 700, "result_days": 3, "collection_notes": "3 ml Whole blood/EDTA"},
        {"name": "Anti Lambda", "price": 700, "result_days": 3, "collection_notes": "3 ml Whole blood/EDTA"},
        {"name": "CD 10", "price": 1200, "result_days": 3, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "CD 103", "price": 1200, "result_days": 3, "collection_notes": "3 ml Whole blood/EDTA"},
        {"name": "CD 11c", "price": 1200, "result_days": 3, "collection_notes": "3 ml Whole blood/EDTA"},
        {"name": "CD 13", "price": 1200, "result_days": 3, "collection_notes": "3 ml Whole blood/EDTA"},
        {"name": "CD 14", "price": 1200, "result_days": 3, "collection_notes": "3 ml Whole blood/EDTA"},
        {"name": "CD 16", "price": 1200, "result_days": 3, "collection_notes": "3 ml Whole blood/EDTA"},
        {"name": "CD 19", "price": 1200, "result_days": 3, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "CD 20", "price": 1200, "result_days": 3, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "CD 200", "price": 1200, "result_days": 3, "collection_notes": "2 ml EDTA blood"},
        {"name": "CD 22", "price": 1200, "result_days": 3, "collection_notes": "3 ml Whole blood/EDTA"},
        {"name": "CD 23", "price": 1200, "result_days": 3, "collection_notes": "3 ml Whole blood/EDTA"},
        {"name": "CD 25", "price": 1200, "result_days": 3, "collection_notes": "3.0 ml EDTA blood"},
        {"name": "CD 3", "price": 1200, "result_days": 3, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "CD 33", "price": 1200, "result_days": 3, "collection_notes": "3.0 ml EDTA blood"},
        {"name": "CD 34", "price": 1200, "result_days": 3, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "CD 4", "price": 1200, "result_days": 3, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "CD 41", "price": 1200, "result_days": 3, "collection_notes": "3.0 ml EDTA blood"},
        {"name": "CD 5", "price": 1200, "result_days": 3, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "CD 55", "price": 1200, "result_days": 3, "collection_notes": "3.0 ml EDTA blood"},
        {"name": "CD 56", "price": 1200},
        {"name": "CD 59", "price": 1700, "result_days": 3, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "CD 7", "price": 1200, "result_days": 3, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "CD 79a", "price": 1200, "result_days": 3, "collection_notes": "3 ml Whole blood/EDTA"},
        {"name": "CD 79b", "price": 1200, "result_days": 3, "collection_notes": "3 ml Whole blood/EDTA"},
        {"name": "CD 8", "price": 1200, "result_days": 3, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "CD38", "price": 1200, "result_days": 3, "collection_notes": "1.0 ml EDTA blood"},
        {"name": "CD4/CD8 Ratio", "price": 1600, "result_days": 5, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "CD56", "price": 1200, "result_days": 3, "collection_notes": "5 ml whole blood /Edta refrigerted"},
        {"name": "FMC-7", "price": 600, "result_days": 3, "collection_notes": "3 ml Whole blood/EDTA"},
        {"name": "MPO", "price": 700, "result_days": 3, "collection_notes": "3.0 ml EDTA blood"},
    ],
    "Iron Profile": [
        {"name": "Ferritin", "price": 400, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Iron (Serum)", "price": 320, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Serum Transferrin", "price": 1400, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "TIBC", "price": 440, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Transferrin Saturation", "price": 500, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
    ],
    "Kidney Profile": [
        {"name": "Albumin / creatinine ratio", "price": 200, "result_days": 1, "collection_notes": "24 hrs. Urine"},
        {"name": "BUN", "price": 120, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Ca++", "price": 220, "result_days": 1, "collection_notes": "2 ml serum, refrigerated,  avoid hemolysis"},
        {"name": "Calcium (Total)", "price": 200, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Creatinine (Serum)", "price": 150, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Cystatin C", "price": 1500, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Cystatin C in urine", "price": 2500, "result_days": 15, "collection_notes": "5ml. fresh urine"},
        {"name": "eGFR (Glomerular filtration", "price": 200, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "K (Potassium)", "price": 160, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Magnesium (Mg) serum", "price": 260, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Microalbuminuria", "price": 350, "result_days": 1, "collection_notes": "urine"},
        {"name": "Na (Sodium)", "price": 160, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "PO4 (Phosphorus)", "price": 160, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Urea", "price": 120, "result_days": 1, "collection_notes": "Serum"},
        {"name": "Uric Acid", "price": 200, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
    ],
    "Lipid Profile": [
        {"name": "Apolipoprotein  A1", "price": 750, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Apolipoprotein  B", "price": 750, "result_days": 7, "collection_notes": "1.0 ml. Serum"},
        {"name": "Cholesterol", "price": 200, "result_days": 1, "collection_notes": "1.0 ml. Serum 12 hours Fasting"},
        {"name": "HDL", "price": 200, "result_days": 1, "collection_notes": "1.0 ml. Serum 12 hours Fasting"},
        {"name": "LDL", "price": 200, "result_days": 1, "collection_notes": "1.0 ml. Serum 12 hours Fasting"},
        {"name": "Lipoprotein  a", "price": 1300, "result_days": 3, "collection_notes": "1.0 ml. Serum"},
        {"name": "Lipoprotein  b", "price": 1000, "result_days": 3, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Triglycerides", "price": 200, "result_days": 1, "collection_notes": "1.0 ml. Serum 12 hours Fasting"},
        {"name": "VLDL", "price": 150, "result_days": 1, "collection_notes": "1.0 ml. Serum 12 hours Fasting"},
    ],
    "Liver Profile": [
        {"name": "5- Nucleotidase", "price": 1300, "result_days": 5, "collection_notes": "1.0 ml. Serum"},
        {"name": "A/G Ratio", "price": 300, "result_days": 1, "collection_notes": "Calculation"},
        {"name": "Albumin (ALB)", "price": 100, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Alkaline Phosphatase (ALP)", "price": 150, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "ALT (SGPT)", "price": 150, "result_days": 1, "collection_notes": "Serum 1.0 ml. Refrigerated"},
        {"name": "AST (SGOT)", "price": 150, "result_days": 1, "collection_notes": "Serum 1.0 ml. Refrigerated"},
        {"name": "Bilirubin Direct", "price": 100, "result_days": 1, "collection_notes": "Serum 1.0 ml. Refrigerated"},
        {"name": "Bilirubin Indirect", "price": 0, "result_days": 1, "collection_notes": "Calculation"},
        {"name": "Bilirubin Total", "price": 200, "result_days": 1, "collection_notes": "Serum 1.0 ml. Refrigerated"},
        {"name": "GGT (Gamma-glutamyl transferase)", "price": 200, "result_days": 1, "collection_notes": "Serum 1.0 ml. Refrigerated"},
        {"name": "Globulin", "price": 300, "result_days": 1, "collection_notes": "Calculation"},
        {"name": "Total Protein", "price": 120, "result_days": 1, "collection_notes": "Serum 1.0 ml. Refrigerated. 6-8  hrs.fasting"},
    ],
    "Molecular Biology": [
        {"name": "HLA-B51 by PCR", "price": 2500, "result_days": 7, "collection_notes": "2 ml EDTA blood"},
        {"name": "CMV DNA by PCR (Qualit)", "price": 1600, "result_days": 5, "collection_notes": "2ml  plasma/Edta"},
        {"name": "CMV DNA by PCR (Quanti)", "price": 1600, "result_days": 5, "collection_notes": "5 ml Edta blood in vacutainer separated & rapidly, avoid"},
        {"name": "Diarrhea Panel (bacterial panel)", "price": 3500, "result_days": 3, "collection_notes": "Stool ot rectal swab"},
        {"name": "Diarrhea Panel (Parasitic panel)", "price": 2500, "result_days": 3, "collection_notes": "Stool ot rectal swab"},
        {"name": "Diarrhea Panel (Viral panel)", "price": 2500, "result_days": 3, "collection_notes": "Stool ot rectal swab"},
        {"name": "Duchenne muscle dystrophy", "price": 2800, "result_days": 15, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Epstein Barr virus (EBV) by pcr", "price": 1500, "result_days": 5, "collection_notes": "2ml  plasma/Edta"},
        {"name": "FMF (MEFV Gene Mutation) by PCR", "price": 4000},
        {"name": "FMF by PCR", "price": 4000, "result_days": 10, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "FMF Gene Mutation", "price": 4000, "result_days": 10, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "Fragile X chromosome by PCR", "price": 6000, "result_days": 20, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "HBV - DNA (Qualitative) by PCR", "price": 2000, "result_days": 3, "collection_notes": "5 ml blood in vacutainer separated & rapidly, avoid hemolysis"},
        {"name": "HBV - DNA (Quantitative) by PCR", "price": 2000, "result_days": 3, "collection_notes": "5 ml blood in vacutainer separated & rapidly, avoid hemolysis"},
        {"name": "HCV - RNA (Qualitative) by PCR", "price": 1500, "result_days": 3, "collection_notes": "5 ml blood in vacutainer separated & rapidly, avoid hemolysis"},
        {"name": "HCV - RNA (Quantitative) by PCR", "price": 1500, "result_days": 3, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "HCV genotyping", "price": 2800, "result_days": 5, "collection_notes": "5 ml blood in vacutainer separated & rapidly, avoid hemolysis"},
        {"name": "HCV in liver biopsy by (ISH)", "price": 1000, "result_days": 4, "collection_notes": "Liver biopsy on 10 % Formalin"},
        {"name": "Herpes family Panel by PCR", "price": 3000, "result_days": 3, "collection_notes": "Whole blood /EDTA or CSF"},
        {"name": "HGV-RNA by PCR", "price": 1400, "result_days": 15, "collection_notes": "5 ml blood in vacutainer separated & rapidly, avoid hemolysis"},
        {"name": "HIV  DNA  by PCR (Qualit)", "price": 5500, "result_days": 2, "collection_notes": "2.0 ml. EDTA plasma - refrigerated"},
        {"name": "HIV by PCR (Qualit) spain", "price": 6000, "result_days": 11, "collection_notes": "2 ml Whole blood /EDTA"},
        {"name": "HIV by PCR (Quantit) spain", "price": 6000, "result_days": 10, "collection_notes": "2 ml Whole blood /EDTA"},
        {"name": "HIV by Western Blott", "price": 4000, "result_days": 7, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "HIV-1 DNA by PCR (Quantit)", "price": 6000, "result_days": 2, "collection_notes": "2.0 ml. EDTA plasma - refrigerated"},
        {"name": "HLA B27 by PCR", "price": 2300, "result_days": 7, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "HLA B5", "price": 2300, "result_days": 7, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "HLA Class l (ABC) by PCR", "price": 10000, "result_days": 10, "collection_notes": "2 ml Whole blood /EDTA"},
        {"name": "HLA Class ll (DQ) by PCR", "price": 4000, "result_days": 10, "collection_notes": "2 ml Whole blood /EDTA"},
        {"name": "HLA Class ll (DR) by PCR", "price": 4000, "result_days": 10, "collection_notes": "10 ml EDTA blood"},
        {"name": "HLA-B51/B52 genotype", "price": 4000, "result_days": 15, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "HLA-DQ2/HLA-DQ8", "price": 4000, "result_days": 10, "collection_notes": "10 ml EDTA blood"},
        {"name": "HLA-Typing class I (A) by PCR", "price": 4000, "result_days": 10, "collection_notes": "2 ml Whole blood /EDTA"},
        {"name": "HLA-Typing class I (B) by PCR", "price": 4000, "result_days": 10, "collection_notes": "2 ml Whole blood /EDTA"},
        {"name": "HLA-Typing class I (C) by PCR", "price": 4000, "result_days": 10, "collection_notes": "2 ml Whole blood /EDTA"},
        {"name": "HSV (I) DNA by PCR", "price": 1500, "result_days": 3, "collection_notes": "5 ml blood in vacutainer separated & rapidly, avoid hemolysis"},
        {"name": "HSV (II) DNA by PCR", "price": 1500, "result_days": 3, "collection_notes": "5 ml blood in vacutainer separated & rapidly, avoid hemolysis"},
        {"name": "Human Papilloma Virus (HPV)(28", "price": 3500, "result_days": 5, "collection_notes": "Vaginal swab transport media"},
        {"name": "Human Papilloma Virus 16 & 18", "price": 4000, "result_days": 5, "collection_notes": "Vaginal swab transport media"},
        {"name": "karyotyping for amniocentesis", "price": 5000, "result_days": 30, "collection_notes": "20 ml Amniotic fluid"},
        {"name": "Karyotyping of Products of", "price": 2200, "result_days": 20, "collection_notes": "tissue cell , missed abortion"},
        {"name": "Karyotyping study", "price": 1700, "result_days": 30, "collection_notes": "5.0 ml. Heparin blood"},
        {"name": "Karyotyping with high resolution", "price": 2300, "result_days": 30, "collection_notes": "5.0 ml. Heparin blood"},
        {"name": "Lactose intolerance by PCR", "price": 1600, "result_days": 5, "collection_notes": "2 ml EDTA blood"},
        {"name": "Respiratory Syncytial Virus", "price": 2500, "result_days": 2, "collection_notes": "Nasal Swab or Nasopharyngeal Swab"},
        {"name": "Salmonella typhi  IgG", "price": 700, "result_days": 4, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Salmonella typhi IgM", "price": 700, "result_days": 4, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "STD Panel by PCR", "price": 5500, "result_days": 4, "collection_notes": "Urine for male and Genital swab for female"},
        {"name": "TB - DNA by PCR", "price": 2000, "result_days": 4, "collection_notes": "3 ml EDTA plasma or any biological fluid (e.g. sputum - urine)"},
        {"name": "Triple test for HCV-RNA", "price": 2800, "result_days": 10, "collection_notes": "5.0 ml serum and  plasma edta"},
        {"name": "Vaginal Panel by PCR", "price": 3000, "result_days": 4, "collection_notes": "Vaginal swab transport media"},
    ],
    "Pancreas Hormones": [
        {"name": "Aldolase", "price": 950, "result_days": 7, "collection_notes": "2ml. frozen Serum in plastic tube frozen, avoid hemolysis"},
        {"name": "Amylase (Urine)", "price": 400, "result_days": 5, "collection_notes": "24 hrs. Urine in alkalinized container"},
        {"name": "Amylase in (serum)", "price": 400, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "C-Peptide (Fasting)", "price": 900, "result_days": 1, "collection_notes": "1.0 ml serum  or  heparinized plasma"},
        {"name": "C-Peptide (Postprandial)", "price": 900, "result_days": 1, "collection_notes": "1.0 ml serum  or  heparinized plasma"},
        {"name": "C-Peptide (Random)", "price": 900, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "C-Peptide (Urine)", "price": 850, "result_days": 1, "collection_notes": "24hr urine without preservative keeping the specimen"},
        {"name": "Fecal Pancreatic Elastase 1", "price": 3500, "result_days": 8, "collection_notes": "Stool"},
        {"name": "Gastrin", "price": 2400, "result_days": 4, "collection_notes": "1.0 ml. fasting frozen serum"},
        {"name": "Glucagon", "price": 2700, "result_days": 20},
        {"name": "Insulin (120 Min.)", "price": 400, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Insulin (180 Min.)", "price": 400, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Insulin (30 Min.)", "price": 400, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Insulin (60 Min.)", "price": 400, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Insulin (Fasting)", "price": 400, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Insulin level (p.p)", "price": 400, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Lipase in serum", "price": 370, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
    ],
    "Parathyroid Hormones": [
        {"name": "Parathormone (PTH)", "price": 430, "result_days": 1, "collection_notes": "2.0 ml. EDTA plasma - refrigerated or frozen"},
    ],
    "Pregnancy Tests": [
        {"name": "BHCG (Quantitative)", "price": 400, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Pregnancy in serum Qualit.", "price": 170, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Pregnancy in urine  Qualit.", "price": 150, "result_days": 1, "collection_notes": "urine"},
    ],
    "Protein Electrophoresis": [
        {"name": "Protein electrophoresis", "price": 750, "result_days": 4, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Protein Electrophoresis in Urine", "price": 1800, "result_days": 5, "collection_notes": "urine"},
    ],
    "Semen Examination": [
        {"name": "Alpha Glucosidase in semen", "price": 1000, "result_days": 10, "collection_notes": "Fresh semen"},
        {"name": "Beta Galactosidase in semen", "price": 1650, "result_days": 5, "collection_notes": "Fresh semen"},
        {"name": "Fructose in semen", "price": 400, "result_days": 1, "collection_notes": "Fresh semen"},
        {"name": "Semen Examination", "price": 350, "result_days": 1, "collection_notes": "Semen"},
        {"name": "Semen peroxidase", "price": 400, "result_days": 1, "collection_notes": "Semen"},
        {"name": "Sperm DNA fragmentation", "price": 4660, "result_days": 10, "collection_notes": "Fresh semen without contamination, sperm count > 1 mill."},
    ],
    "Separate": [
        {"name": "Acid Phosphatase (Prostatic)", "price": 400, "result_days": 1, "collection_notes": "1 ml Serum/ Refrigerated"},
        {"name": "Acid Phosphatase (Total)", "price": 400, "result_days": 5, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "ACID-FAST STAIN (ZN Film) 3", "price": 350, "result_days": 1, "collection_notes": "Fluid/Sputum"},
        {"name": "Acrosin Activity", "price": 450, "result_days": 6, "collection_notes": "Fresh semen"},
        {"name": "Adenosine Deaminase (ADA) in", "price": 700, "result_days": 7, "collection_notes": "Fluid"},
        {"name": "Adenosine Deaminase (ADA) in", "price": 700, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Albumin (Urine)", "price": 120, "result_days": 1, "collection_notes": "urine"},
        {"name": "Alpha-1 antitrypsin in blood", "price": 1000, "result_days": 10, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Alpha-1 antitrypsin in stool", "price": 1200, "result_days": 10, "collection_notes": "Stool"},
        {"name": "Alpha-2 macroglobulin", "price": 1200, "result_days": 4, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Ammonia", "price": 600, "result_days": 1, "collection_notes": "EDTA frozen, heparinized plasma , avoid hemolysis"},
        {"name": "Amyloid A protein", "price": 2500, "result_days": 5, "collection_notes": "2 ml serum, frozen"},
        {"name": "Anal adhesive strip", "price": 300},
        {"name": "Angiotensin Converting Enz.", "price": 1500, "result_days": 5, "collection_notes": "2 ml serum/ refrigerated"},
        {"name": "Anti Adrenal Ab", "price": 1500, "result_days": 15, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Anti Diuretic hormone (ADH)", "price": 2400, "result_days": 10, "collection_notes": "2 ml Frozen plasma/EDTA"},
        {"name": "Anti Rabies Abs", "price": 2700, "result_days": 15, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Aspergillus Galactomannan", "price": 2000, "result_days": 10, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Bartonnella Henselae", "price": 1060, "result_days": 9, "collection_notes": "2 ml serum, frozen"},
        {"name": "Bile Acids, serum", "price": 1700, "result_days": 7, "collection_notes": "2 ml serum, frozen"},
        {"name": "Bilharziasis Ag (urine)", "price": 500, "result_days": 1, "collection_notes": "5ml. fresh urine"},
        {"name": "Bilharziasis Antigen (serum)", "price": 400, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Biotinidase Activity", "price": 1400, "result_days": 30, "collection_notes": "2 ml serum, frozen"},
        {"name": "Body fluid Examination", "price": 1000, "result_days": 1, "collection_notes": "Fluid"},
        {"name": "Bone marrow Biobsy", "price": 2000, "result_days": 15, "collection_notes": "Bone marrow Biobsy"},
        {"name": "Bone marrow Film: Consultation", "price": 1000},
        {"name": "Borrelia Burgdorferi IgG Abs", "price": 1300, "result_days": 15, "collection_notes": "2 ml serum, frozen"},
        {"name": "Borrelia Burgdorferi IgM Abs", "price": 1300, "result_days": 15, "collection_notes": "2 ml serum, frozen"},
        {"name": "Bronchial Lavage Examination C/S", "price": 450, "result_days": 5, "collection_notes": "Bronchial Lavage"},
        {"name": "Bronchial Lavage Film For AFB", "price": 200, "result_days": 2, "collection_notes": "Bronchial Lavage Film"},
        {"name": "Brucella IgG", "price": 800, "result_days": 10, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Brucella IgM", "price": 700, "result_days": 10, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "BUN/Creatinine ratio", "price": 220, "result_days": 1, "collection_notes": "24 hrs. Urine or spontaneous urine"},
        {"name": "Calcium/creatinine ratio", "price": 350, "result_days": 1, "collection_notes": "24 hrs. Urine"},
        {"name": "Calprotectin in stool (Qual)", "price": 1200, "result_days": 2, "collection_notes": "Stool"},
        {"name": "Calprotectin in stool (Quant)", "price": 1750, "result_days": 3, "collection_notes": "Stool"},
        {"name": "Catecholamines Plasma", "price": 2600, "result_days": 10, "collection_notes": "2.0 ml. frozen EDTA plasma"},
        {"name": "Ceruloplasmin", "price": 550, "result_days": 3, "collection_notes": "Serum 2.0 ml. Refrigerated"},
        {"name": "Chlamydia lgM", "price": 1000},
        {"name": "Chlamydia pneumonia IgG", "price": 1500, "result_days": 10, "collection_notes": "2 ml serum, frozen"},
        {"name": "Chlamydia pneumonia IgM", "price": 1500, "result_days": 10, "collection_notes": "2 ml serum, frozen"},
        {"name": "Chlamydia Trachomatis IgG", "price": 1600, "result_days": 10, "collection_notes": "2 ml serum, frozen"},
        {"name": "Chlamydia Trachomatis IgM", "price": 1600, "result_days": 10, "collection_notes": "2 ml serum, frozen"},
        {"name": "Clostridium difficile", "price": 1800, "result_days": 2, "collection_notes": "stool"},
        {"name": "Creatinine Clearance", "price": 300, "result_days": 1, "collection_notes": "1.0 ml. Serum and 24hrs Urine"},
        {"name": "CRP", "price": 350, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Cryoglobulins", "price": 250, "result_days": 2, "collection_notes": "2 ml serum on tube should be warmed before use donot"},
        {"name": "CSF -Cells", "price": 250, "result_days": 1, "collection_notes": "2 ml csf fluid"},
        {"name": "Cytology Examination", "price": 1300, "result_days": 5, "collection_notes": "Fluid"},
        {"name": "DNA by sequencer", "price": 9000, "result_days": 30, "collection_notes": "5 ml Whole blood / EDTA"},
        {"name": "Dopamine Beta hydroxylase", "price": 1600, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Estrogen Receptors", "price": 2200, "result_days": 15, "collection_notes": "Biobsy"},
        {"name": "FFAs (Free fatty acid)", "price": 6500, "result_days": 22, "collection_notes": "2 ml serum, frozen"},
        {"name": "Filaria Film", "price": 400, "result_days": 1, "collection_notes": "10 ml EDTA blood"},
        {"name": "Free light Kappa/Lambda ratio", "price": 2300, "result_days": 4, "collection_notes": "2 ml serum, frozen"},
        {"name": "Fructosamine", "price": 400, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Fungus examination by KOH", "price": 250, "result_days": 1, "collection_notes": "skin. nail , hair or any part of body"},
        {"name": "Galactose", "price": 1600, "result_days": 3, "collection_notes": "1.0 ml serum or plasma"},
        {"name": "Glycine level", "price": 3000, "result_days": 20, "collection_notes": "3 ml Whole blood /EDTA"},
        {"name": "Growth Hormone (basal)", "price": 450, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "H.pylori Ag in Stool (Quanti)", "price": 650, "result_days": 3, "collection_notes": "Stool"},
        {"name": "H.pylori Line IgG", "price": 1750, "result_days": 7, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "hs-CRP", "price": 350},
        {"name": "IGF-1", "price": 2500, "result_days": 10, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "IGFBP-3", "price": 2500, "result_days": 7, "collection_notes": "2 ml serum, frozen"},
        {"name": "Ketone Bodies in Blood", "price": 300},
        {"name": "Lactate in blood", "price": 400, "result_days": 5, "collection_notes": "2ml  plasma/Edta"},
        {"name": "Lamotrigine", "price": 1570, "result_days": 10, "collection_notes": "2 ml serum, frozen"},
        {"name": "Leptin", "price": 2500, "result_days": 10, "collection_notes": "2 ml serum, frozen"},
        {"name": "Levetiracetam (kepra)", "price": 2020, "result_days": 10, "collection_notes": "2 ml serum, frozen"},
        {"name": "Link index parameter", "price": 1700, "result_days": 7, "collection_notes": "1.0 ml serum + 2 ml frozen CSF"},
        {"name": "Lipid Electrophoresis", "price": 1200, "result_days": 5, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Malaria Antigen (film)", "price": 400, "result_days": 2, "collection_notes": "2.0 ml EDTA blood + 4 Film from fresh blood"},
        {"name": "Malaria IgG Ab", "price": 1600, "result_days": 10, "collection_notes": "1.0 ml. Serum"},
        {"name": "Mumps Abs(IgG)", "price": 1400, "result_days": 10, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Noradrenaline in urine", "price": 3000},
        {"name": "Organic acid (qualiti)", "price": 0, "result_days": 35, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Organic acid in urine", "price": 3500, "result_days": 22, "collection_notes": "24 hrs. urine 10 ml 6 N. HCL"},
        {"name": "Osteocalcin Level", "price": 1700, "result_days": 10, "collection_notes": "2 ml serum, frozen"},
        {"name": "Oxalate (urine)", "price": 1600, "result_days": 5, "collection_notes": "24 hrs. urine 10 ml 6 N. HCL"},
        {"name": "Phenylalanine (PKU)", "price": 1500, "result_days": 16, "collection_notes": "1.0 ml Frozen EDTA plasma"},
        {"name": "Plasminogen", "price": 2200, "result_days": 1},
        {"name": "Plasminogen Activator inhibitor", "price": 2200, "result_days": 1},
        {"name": "Protein C Activity", "price": 1000, "result_days": 3, "collection_notes": "2 ml frozen. citrated plasma platelet poor in plastic tube"},
        {"name": "Protein S Activity", "price": 1000, "result_days": 3, "collection_notes": "2 ml frozen. citrated plasma platelet poor in plastic tube"},
        {"name": "Protein/creatinine ratio", "price": 250, "result_days": 1, "collection_notes": "urine / random sample or 24 hrs sample"},
        {"name": "Pyruvate Kinase PK", "price": 1000, "result_days": 7, "collection_notes": "2 ml EDTA blood"},
        {"name": "Reducing Suger In Stool", "price": 270, "result_days": 1, "collection_notes": "Stool"},
        {"name": "Rota virus antigen", "price": 500, "result_days": 1, "collection_notes": "Fresh stool"},
        {"name": "S.Bicarbonate (blood)", "price": 550, "result_days": 1, "collection_notes": "2 ml anaerobic heparinized blood send immed."},
        {"name": "Sickling test", "price": 400, "result_days": 2, "collection_notes": "1.0 ml EDTA blood"},
        {"name": "Stone Analysis", "price": 550, "result_days": 1, "collection_notes": "Stone"},
        {"name": "Total Lipid", "price": 450, "result_days": 1, "collection_notes": "1.0 ml. Serum 12 hours Fasting"},
        {"name": "TPHA", "price": 250, "result_days": 8, "collection_notes": "1.0 ml. Serum"},
        {"name": "Urate in Urine", "price": 550},
        {"name": "Urea Breath Test", "price": 2100, "result_days": 3, "collection_notes": "Special test"},
        {"name": "Uric Acid (Urine)", "price": 120, "result_days": 1, "collection_notes": "24 hrs. Urine"},
        {"name": "Uric acid/creatinine ratio", "price": 300, "result_days": 1, "collection_notes": "24 hrs. Urine"},
        {"name": "VDRL", "price": 250, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
    ],
    "SEROLOGY": [
        {"name": "Brucella Test", "price": 300, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "H.pylori  IgA  (quantit)", "price": 560, "result_days": 1, "collection_notes": "Serum 1.0 ml. Refrigerated"},
        {"name": "H.pylori  IgG  (qualiti)", "price": 300, "result_days": 2, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "H.pylori  IgG  (quantit)", "price": 550, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "H.pylori  IgM  (quantit)", "price": 700, "result_days": 2, "collection_notes": "1.0 ml. Serum"},
        {"name": "H.pylori Ag in Stool (Qualit)", "price": 560, "result_days": 1, "collection_notes": "Stool"},
        {"name": "RF (Qualit)", "price": 160, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "RF (Quantit)", "price": 280, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Widal Test", "price": 250, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
    ],
    "Serum Electrolytes": [
        {"name": "Chloride (CL) in serum", "price": 300, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Osmolality. (serum)", "price": 350, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
    ],
    "Stool Examination": [
        {"name": "Stool Examination", "price": 150, "result_days": 1, "collection_notes": "Stool"},
    ],
    "Suprarenal Hormones": [
        {"name": "11-Desoxycortisol", "price": 1800, "result_days": 20, "collection_notes": "serum/ Frozen"},
        {"name": "17 OH Progesterone", "price": 2200, "result_days": 4, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "5-HIAA (hydroxyindoleacetic", "price": 1700, "result_days": 7, "collection_notes": "24 hrs. urine 10 ml 6 N. HCL"},
        {"name": "ACTH (AM)", "price": 900, "result_days": 2, "collection_notes": "Frozen plasma/EDTA in plastic tube"},
        {"name": "ACTH (PM)", "price": 900, "result_days": 3, "collection_notes": "Frozen plasma/EDTA in plastic tube"},
        {"name": "ACTH (Random)", "price": 900, "result_days": 2, "collection_notes": "Frozen plasma/EDTA in plastic tube"},
        {"name": "ACTH level after Inj.", "price": 900, "result_days": 1, "collection_notes": "1.0 ml Frozen EDTA plasma"},
        {"name": "Adrenaline (Epinephrine)", "price": 3000, "result_days": 4, "collection_notes": "Frozen heparinized fasting plasma. Avoid coffee, tea etc before"},
        {"name": "Aldosterone", "price": 2000, "result_days": 10, "collection_notes": "2 ml serum, frozen"},
        {"name": "Catecholamines free fraction", "price": 2500, "result_days": 10, "collection_notes": "24 hrs. urine 10 ml 6 N. HCL"},
        {"name": "Cortisol (AM)", "price": 350, "result_days": 1, "collection_notes": "1.0 ml. Serum (9 AM)"},
        {"name": "Cortisol (PM)", "price": 350, "result_days": 1, "collection_notes": "1.0 ml. Serum (9 PM)"},
        {"name": "Cortisol (random)", "price": 350},
        {"name": "Cortisol (Urine)", "price": 350, "result_days": 4, "collection_notes": "24 hrs. urine 10 ml 6 N. HCL"},
        {"name": "Cortisol level after Inj.", "price": 350, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Cortisol level before Inj.", "price": 350, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Dopamine", "price": 4000, "result_days": 15, "collection_notes": "Frozen EDTA fasting plasma"},
        {"name": "Free metanephrine", "price": 3500, "result_days": 10, "collection_notes": "2 ml plasma EDTA"},
        {"name": "Free Normetanephrine", "price": 3500, "result_days": 10, "collection_notes": "2ml  plasma/Edta"},
        {"name": "Ghrelin", "price": 4400, "result_days": 60, "collection_notes": "2 ml serum, frozen"},
        {"name": "Homovanillic acid (HVA)", "price": 2700, "result_days": 15, "collection_notes": "24 hrs. urine 10 ml 6 N. HCL"},
        {"name": "Metanephrine in urine", "price": 3500, "result_days": 10, "collection_notes": "24 hrs. urine 10 ml 6 N. HCL, Avoid coffee, tea etc before"},
        {"name": "Noradrenaline (Norepinephrine)", "price": 3000, "result_days": 4, "collection_notes": "Frozen heparinized fasting plasma. Avoid coffee, tea etc before"},
        {"name": "Normetanephrine in urine", "price": 4000, "result_days": 10, "collection_notes": "24 hrs. urine 10 ml 6 N. HCL, Avoid coffee, tea etc before"},
        {"name": "Plasma Renin", "price": 2500, "result_days": 18, "collection_notes": "1.0 ml Frozen EDTA plasma"},
        {"name": "Serotonin", "price": 3500, "result_days": 10, "collection_notes": "2 ml serum, frozen"},
        {"name": "VMA (Urine)", "price": 2000, "result_days": 1, "collection_notes": "24 hrs. urine 10 ml 6 N. HCL"},
    ],
    "Thyroid Hormones": [
        {"name": "Anti Microsomal/peroxidase Ab.", "price": 600, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Anti Thyroid Antibodies", "price": 635, "result_days": 2, "collection_notes": "2 ml serum/ refrigerated"},
        {"name": "Anti-Thyroglobulin Abs", "price": 650, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Calcitonin", "price": 1800, "result_days": 7, "collection_notes": "1.0 ml. frozen fasting serum"},
        {"name": "FT3", "price": 270, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "FT4", "price": 270, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "FTI  (Free Thyroxin Index)", "price": 300, "result_days": 3, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "PBI (Protein Bound Iodine)", "price": 300, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Reverse T3 (rT3)", "price": 2500, "result_days": 15, "collection_notes": "2 ml serum, frozen"},
        {"name": "T3 (Total)", "price": 270, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "T3 Uptake", "price": 270, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "T4 (Total)", "price": 270, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Thyroglobulin (Tg)", "price": 1000, "result_days": 1, "collection_notes": "1.0 ml serum  or  heparinized plasma"},
        {"name": "TSH", "price": 330, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "TSH Receptor Ab (Anti-TSHR)", "price": 2000, "result_days": 10, "collection_notes": "2 ml serum, refrigerated"},
    ],
    "TORCH Screen": [
        {"name": "CMV IgG", "price": 350, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "CMV IgM", "price": 350, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Epstein Barr virus (EBV - VCA", "price": 800, "result_days": 2, "collection_notes": "1.0 ml. Serum"},
        {"name": "Epstein Barr virus (EBV- VCA", "price": 650, "result_days": 2, "collection_notes": "1.0 ml. Serum"},
        {"name": "Herpes (I) IgG", "price": 300, "result_days": 2, "collection_notes": "1.0 ml. Serum"},
        {"name": "Herpes (I) IgM", "price": 300, "result_days": 2, "collection_notes": "1.0 ml. Serum"},
        {"name": "Herpes (II)  IgG", "price": 300, "result_days": 2, "collection_notes": "1.0 ml. Serum"},
        {"name": "Herpes (II)  IgM", "price": 300, "result_days": 2, "collection_notes": "1.0 ml. Serum"},
        {"name": "Rubella IgG", "price": 300, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Rubella IgM", "price": 300, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Toxo IgG", "price": 300, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Toxo IgM", "price": 300, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Toxo IHA", "price": 120, "result_days": 1},
    ],
    "Trace Elements": [
        {"name": "Aluminium (blood)", "price": 6000, "result_days": 20, "collection_notes": "2.0 ml. heparinized plasma."},
        {"name": "Aluminium (Hair)", "price": 2500, "result_days": 15, "collection_notes": "5 gram of hair"},
        {"name": "Aluminium (urine)", "price": 6000, "result_days": 20, "collection_notes": "Urine"},
        {"name": "Arsenic (blood)", "price": 5000, "result_days": 15, "collection_notes": "Serum"},
        {"name": "Arsenic (Hair)", "price": 1500, "result_days": 15, "collection_notes": "5 gram of hair"},
        {"name": "Arsenic (urine)", "price": 0, "result_days": 1, "collection_notes": "urine / random sample or 24 hrs sample"},
        {"name": "Cadmium (blood)", "price": 1400, "result_days": 7, "collection_notes": "Heparinized Blood"},
        {"name": "Cadmium (urine)", "price": 1400, "result_days": 7, "collection_notes": "urine"},
        {"name": "Chromium (blood)", "price": 700, "result_days": 1, "collection_notes": "Serum"},
        {"name": "Chromium (urine)", "price": 700, "result_days": 1},
        {"name": "Cobalt (blood)", "price": 1500, "result_days": 7, "collection_notes": "5.0 ml. Heparin blood"},
        {"name": "Cobalt (urine)", "price": 1500, "result_days": 7, "collection_notes": "24 hours urine"},
        {"name": "Copper (blood)", "price": 550, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Copper (urine)", "price": 550, "result_days": 1, "collection_notes": "24 hrs. urine 10 ml 6 N. HCL"},
        {"name": "heavy metals (in hair)", "price": 12000, "result_days": 35, "collection_notes": "5 gram of hair"},
        {"name": "Lead (blood)", "price": 1500, "result_days": 15, "collection_notes": "5.0 ml. frozen EDTA plasma"},
        {"name": "Lead (hair)", "price": 2000, "result_days": 20, "collection_notes": "5 gram of hair"},
        {"name": "Lead (urine)", "price": 1500, "result_days": 10, "collection_notes": "24 hours urine"},
        {"name": "Mercury (hair)", "price": 1000, "result_days": 15, "collection_notes": "5 gram of hair"},
        {"name": "Mercury (urine)", "price": 1500, "result_days": 12, "collection_notes": "urine / random sample or 24 hrs sample"},
        {"name": "Nickel (blood)", "price": 1200, "result_days": 3, "collection_notes": "1.0 ml. frozen serum"},
        {"name": "Nickel (urine)", "price": 1200, "result_days": 3},
        {"name": "Selenium (blood)", "price": 5000, "result_days": 9},
        {"name": "Selenium (urine)", "price": 5000, "result_days": 1},
        {"name": "Water Examination", "price": 1500, "result_days": 7, "collection_notes": "Water for Examinatin"},
        {"name": "Water Examination (chemical)", "price": 1000, "result_days": 7, "collection_notes": "Water for Examination"},
        {"name": "Zinc (blood)", "price": 550, "result_days": 3, "collection_notes": "1.0 ml. Serum"},
        {"name": "Zinc (urine)", "price": 550, "result_days": 1, "collection_notes": "24 hrs. Urine"},
    ],
    "Tumors Markers": [
        {"name": "AFP", "price": 600, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "B2 Microglobulin (Serum)", "price": 600, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "B2 Microglobulin (Urine)", "price": 1000, "result_days": 1, "collection_notes": "10 ml refrigerated morning urine sample , No preservative"},
        {"name": "Bcl - 2", "price": 1000, "result_days": 15, "collection_notes": "Biobsy"},
        {"name": "BCR-ABL by FISH", "price": 1600, "result_days": 15, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "BCR-ABL by PCR", "price": 5000, "result_days": 10, "collection_notes": "2.0 ml EDTA blood"},
        {"name": "BHCG (TUMOR MARKER)", "price": 400, "result_days": 1, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "BRCA 1 ,2 gene mutation", "price": 19000, "result_days": 35, "collection_notes": "4 tube Whole blood EDTA"},
        {"name": "CA 125", "price": 650, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "CA 15.3", "price": 650, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "CA 19.9", "price": 650, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "CA 27.29", "price": 5000, "result_days": 10, "collection_notes": "2 ml serum, frozen"},
        {"name": "CA 27.29 Antigen", "price": 4500, "result_days": 5, "collection_notes": "2 ml serum, frozen"},
        {"name": "CA 50", "price": 4000, "result_days": 10, "collection_notes": "1.0 ml. Serum"},
        {"name": "CA 72.4", "price": 4500, "result_days": 10, "collection_notes": "2 ml serum, frozen"},
        {"name": "CEA (Carcinoembryonic Antigen)", "price": 550, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "IGHV by Fish", "price": 4000, "result_days": 30, "collection_notes": "2.0 ml. heparinized blood."},
        {"name": "Jak - 2 Exon 12 Mutation", "price": 2500, "result_days": 20, "collection_notes": "1.0 ml serum or plasma"},
        {"name": "Jak - 2(V617F)", "price": 2500, "result_days": 10, "collection_notes": "1.0 ml serum or plasma"},
        {"name": "Kappa light chain in serum", "price": 1700, "result_days": 2, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Kappa light chain in urine", "price": 1800, "result_days": 2, "collection_notes": "urine"},
        {"name": "Lambda Light Chain in serum", "price": 1300, "result_days": 2, "collection_notes": "2 ml serum/ refrigerated"},
        {"name": "Lambda Light Chain in urine", "price": 1600, "result_days": 2, "collection_notes": "urine"},
        {"name": "NSE", "price": 1500, "result_days": 6, "collection_notes": "2 ml serum, frozen"},
        {"name": "Pap Smear", "price": 1300, "result_days": 5, "collection_notes": "swab or slides"},
        {"name": "Pathological Examination", "price": 1700, "result_days": 5, "collection_notes": "Biobsy"},
        {"name": "PSA (Free)", "price": 450, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "PSA (Total)", "price": 300, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "PSA Ratio", "price": 800, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "Schebo test (M2-PK)", "price": 2500, "result_days": 4, "collection_notes": "Stool"},
        {"name": "Urinary Bladder Cancer (UBC)", "price": 2000},
    ],
    "Urine Electrolytes": [
        {"name": "Calcium (Ca) urine", "price": 220, "result_days": 1, "collection_notes": "24 hrs. Urine"},
        {"name": "Chloride (CL) in urine", "price": 300, "result_days": 1, "collection_notes": "24 hrs. Urine"},
        {"name": "Citrate (urine)", "price": 1500, "result_days": 7, "collection_notes": "24 hours urine"},
        {"name": "Magnesium (Mg) in urine", "price": 260, "result_days": 1, "collection_notes": "24 hrs. Urine or spontaneous urine"},
        {"name": "Osmolality. (urine)", "price": 350, "result_days": 1, "collection_notes": "5ml. fresh urine"},
        {"name": "Phosphorus (Ph) urine", "price": 160, "result_days": 1, "collection_notes": "24 hrs. Urine"},
        {"name": "Potassium (k) urine", "price": 160, "result_days": 1, "collection_notes": "24 hrs. Urine"},
        {"name": "Sodium (Na) urine", "price": 170, "result_days": 1, "collection_notes": "24 hrs. Urine"},
    ],
    "Urine Examination": [
        {"name": "Amino Acids in urine", "price": 3500, "result_days": 2, "collection_notes": "10 ml frozen urine sample , No preservative"},
        {"name": "Bence jones protein (Urine)", "price": 300, "result_days": 1, "collection_notes": "Fresh morning urine"},
        {"name": "Creatinine (urine)", "price": 150, "result_days": 1, "collection_notes": "24 hrs. Urine"},
        {"name": "Dysmorphic RBCs in urine", "price": 300, "result_days": 1, "collection_notes": "Fresh urine sample (50 ml)"},
        {"name": "Free light Kappa/Lambda in Urine", "price": 3500, "result_days": 7, "collection_notes": "urine"},
        {"name": "Protein in urine", "price": 150, "result_days": 1, "collection_notes": "24 hours urine"},
        {"name": "STROX in urine", "price": 440, "result_days": 3, "collection_notes": "urine"},
        {"name": "Urine Examination", "price": 120},
    ],
    "Virology": [
        {"name": "Adeno Virus Ab", "price": 700},
        {"name": "Bartonnella Henselae", "price": 1060, "result_days": 15, "collection_notes": "2 ml serum, frozen"},
        {"name": "EBV  (IgG)", "price": 450, "result_days": 2, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "EBV  (IgM)", "price": 450, "result_days": 2, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "EBV- EBNA (IgG)", "price": 450, "result_days": 3, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "EBV- EBNA (IgM)", "price": 450, "result_days": 3, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Entero Virus (Coxsackie A9) IgG", "price": 2000, "result_days": 15, "collection_notes": "2 ml serum, frozen"},
        {"name": "Entero Virus (Coxsackie A9) IgM", "price": 2000, "result_days": 15, "collection_notes": "2 ml serum, frozen"},
        {"name": "Entero Virus (Coxsackie B1-6)", "price": 2000, "result_days": 15, "collection_notes": "2 ml serum, frozen"},
        {"name": "Entero Virus (Coxsackie B1-6)", "price": 2000, "result_days": 15, "collection_notes": "2 ml serum, frozen"},
        {"name": "H1N1 by Real Time PCR", "price": 2500, "result_days": 1, "collection_notes": "Nasal Swab"},
        {"name": "HIV (I,II) Abs", "price": 450, "result_days": 1, "collection_notes": "1.0 ml. Serum"},
        {"name": "HIV Combi Ag/Ab", "price": 500, "result_days": 2},
        {"name": "Human Papilloma Virus (IgG) HPV", "price": 4000, "result_days": 9, "collection_notes": "2.0 ml serum or plasma"},
        {"name": "Malaria IgM Ab", "price": 1600, "result_days": 10, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Measles IgG", "price": 1400, "result_days": 8, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Measles IgM", "price": 1400, "result_days": 8, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Mumps Abs(IgM)", "price": 1400, "result_days": 10, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Parvovirus B19 IgG", "price": 0, "result_days": 10, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Parvovirus B19 IgM", "price": 0, "result_days": 10, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Spike Corona IgG Abs", "price": 700, "result_days": 1, "collection_notes": "1.0 ml serum"},
        {"name": "Spike Corona IgM Abs", "price": 700},
        {"name": "Varicella Zoster (IgA)", "price": 1300, "result_days": 10, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Varicella Zoster (IgG)", "price": 1300, "result_days": 10, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Varicella Zoster (IgM)", "price": 1400, "result_days": 10, "collection_notes": "2 ml serum, refrigerated"},
        {"name": "Viral Ag (Rapid test)", "price": 700, "result_days": 1, "collection_notes": "Nasal Swab"},
        {"name": "Viral PCR-RNA (Qualitative)", "price": 1700, "result_days": 1, "collection_notes": "Nasal Swab"},
        {"name": "Viral PCR-RNA (Qualitative)", "price": 1500, "result_days": 1, "collection_notes": "swab"},
        {"name": "Viral PCR-RNA (Urgently)", "price": 2800},
    ],
    "Vitamins": [
        {"name": "Ascorbic acid in plasma (vitamin", "price": 6000, "result_days": 6, "collection_notes": "2.0 ml.Frozen plasma ( Lithium heparinized or EDTA)"},
        {"name": "Biotin (Vitamin H/ B7 /B8)", "price": 8000, "result_days": 20, "collection_notes": "2 ml serum, frozen"},
        {"name": "Folate (Folic Acid) serum", "price": 1200, "result_days": 4, "collection_notes": "2.0 ml. frozen serum protected from light"},
        {"name": "Index Omega 3", "price": 7000, "result_days": 35, "collection_notes": "Whole blood/EDTA 5 ml"},
        {"name": "Lactoferrin", "price": 2200, "result_days": 15, "collection_notes": "Fresh stool"},
        {"name": "Vitamin A", "price": 4500, "result_days": 17, "collection_notes": "1.0 ml. frozen serum protected from light"},
        {"name": "Vitamin B1", "price": 7000, "result_days": 20, "collection_notes": "3.0 ml EDTA blood"},
        {"name": "Vitamin B12", "price": 1500, "result_days": 1, "collection_notes": "1.0 ml. frozen serum protected from light"},
        {"name": "Vitamin B2", "price": 6000, "result_days": 10, "collection_notes": "2 ml EDTA blood"},
        {"name": "Vitamin B3", "price": 6000, "result_days": 18, "collection_notes": "2 ml serum, frozen"},
        {"name": "Vitamin B5", "price": 8000, "result_days": 35, "collection_notes": "2 ml serum, frozen"},
        {"name": "Vitamin B6", "price": 6000, "result_days": 30, "collection_notes": "5 ml EDTA blood"},
        {"name": "Vitamin C", "price": 6000, "result_days": 17, "collection_notes": "2.0 ml.Frozen plasma ( Lithium heparinized or EDTA)"},
        {"name": "Vitamin D2 (1,25 Dihydroxy)", "price": 2000, "result_days": 10, "collection_notes": "4.0 ml. frozen serum protected from light"},
        {"name": "Vitamin D3(25 Hydroxy Cholecal.)", "price": 1000, "result_days": 2, "collection_notes": "1.0 ml. frozen serum protected from light"},
        {"name": "Vitamin E", "price": 6000, "result_days": 10, "collection_notes": "1.0 ml. frozen serum protected from light"},
        {"name": "Vitamin K", "price": 6000, "result_days": 12, "collection_notes": "2 ml serum, frozen"},
    ],
}
